- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: /home/{{ user_name }}/.ssh
    state: directory
    mode: '0700'
  become: true

- name: copy ssh key
  ansible.builtin.copy:
    src: id_rsa.pub
    dest: /home/{{ user_name }}/.ssh/authorized_keys
    mode: '0600'
  become: true
