- name: Add SSH key to the authorized_keys file
  ansible.posix.authorized_key:
    user: '{{ user_name }}'
    state: present
    key: "{{ lookup('file', 'id_rsa.pub') }}"
    manage_dir: true
  become: true
