- hosts: appservers

  vars:
    nginx_port: 80
    root_dir: /usr/share/nginx/html
    custom_message: 'This is server {{ ansible_hostname }}!'

  tasks:
    - name: install cowsay
      ansible.builtin.apt:
        name: cowsay
        state: latest
        update_cache: yes
      become: true

    - name: make cow say server name
      command: /usr/games/cowsay "{{ custom_message }}"
      register: cowsay_output
      become: true

    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: yes
      become: true

    - name: copy index.html
      ansible.builtin.template:
        src: ../index.html
        dest: '{{root_dir}}/index.html'
      become: true

    - name: copy nginx.conf
      ansible.builtin.template:
        src: ../nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: true

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: true
