- hosts: webservers

  vars:
    nginx_port: 80
    root_dir: /usr/share/nginx/html

  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: yes
      become: true

    - name: copy index.html
      ansible.builtin.template:
        src: ../index.html
        dest: '{{root_dir}}/index.html'
      become: true

    - name: copy nginx.conf
      ansible.builtin.template:
        src: ../nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: true

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: true
